#!/bin/bash
sxhkd &
feh ~/Pictures/Wallpapers/noir.png --bg-fill ~/Pictures/Wallpapers/road.png --bg-fill &
xsetroot -cursor_name left_ptr &
xcompmgr -c -f -n &
setxkbmap -layout us -variant intl &
$HOME/scripts/bspwm_dual_monitor.sh &
$HOME/.config/polybar/launch.sh &
$HOME/.config/conky/launch.sh &
xscreensaver -nosplash &

laptopMonitor=$(xrandr --query | grep 'eDP-1-1')
externalMonitor=$(xrandr --query | grep 'HDMI-0')

if [[ $externalMonitor != *disconnected* ]]; then
	bspc monitor eDP-1-1 -d "Email" "Log" "Music"
	bspc monitor HDMI-0 -d "Internet" "Development" "Extra"
else
	bspc monitor eDP-1-1 -d "Email" "Log" "Music" "Internet" "Development" "Extra"
fi

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bpsc config click_to_focus false

# Dracula Theme
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
